name: Build and push to DO

on:
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v2
      - name: Build and tag API
        working-directory: ./packages/api
        run: docker build -t registry.digitalocean.com/rafasdc/95545-api:$(echo $GITHUB_SHA | head -c7) .
      - name: Build and tag frontend
        working-directory: ./packages/frontend
        run: docker build -t registry.digitalocean.com/rafasdc/95545-frontend:$(echo $GITHUB_SHA | head -c7) .
      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
      - name: Log in to DO Container Registry 
        run: doctl registry login --expiry-seconds 600
      - name: Push API image to DO Container Registry 
        run: docker push registry.digitalocean.com/rafasdc/95545-api:$(echo $GITHUB_SHA | head -c7)
      - name: Push frontend image to DO Container Registry 
        run: docker push registry.digitalocean.com/rafasdc/95545-frontend:$(echo $GITHUB_SHA | head -c7)
