name: Test
on:
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        env:
            DB_CONNECTION_STRING: "mongodb://test:27017"
        steps:
            - uses: actions/checkout@v3
            - name: Install modules
              run: npm i
            - name: Run tests
              working-directory: ./packages/api
              run: npm test
