name: Test
on: push
env: 
  DB_CONNECTION_STRING: "mongodb://localhost:27017"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm i
    - name: Run tests
      working-directory: ./packages/api
      run: npm test
